//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiumClientMobile.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessibilityIds {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessibilityIds() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppiumClientMobile.Properties.AccessibilityIds", typeof(AccessibilityIds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ComMotivistDevelopment_OtpPage_LoginPhoneNumber {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_OtpPage_LoginPhoneNumber", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToEnterNumberScreen_EnteredNumber {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToEnterNumberScreen_EnteredNumber", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToEnterNumberScreen_ExpectedNumber {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToEnterNumberScreen_ExpectedNumber", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_OtpPage_LoginButton {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_OtpPage_LoginButton", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToWriteOtpCodeInsideTextArea_DialogTextMessage {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToWriteOtpCodeInsideTextArea_DialogTextMessage" +
                        "", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckFromMessageDialog_DialogNegativeButton {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckFromMessageDialog_DialogNegativeButton", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_OtpDialogView_ErrorMessageText {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_OtpDialogView_ErrorMessageText", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToOtpEnterOtpCodeScreenWithWaitThreeMinAfterOtpRetry_LoginOtpRetryButton {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToOtpEnterOtpCodeScreenWithWaitThreeMinAfterOt" +
                        "pRetry_LoginOtpRetryButton", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToOtpEnterOtpCodeScreen_OtpEditText {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToOtpEnterOtpCodeScreen_OtpEditText", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToOtpEnterOtpCodeScreen_LoginOtpVerify {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToOtpEnterOtpCodeScreen_LoginOtpVerify", resourceCulture);
            }
        }
        
        internal static string StartAppOtpUIViewController_Allow {
            get {
                return ResourceManager.GetString("StartAppOtpUIViewController_Allow", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMainMissions {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMai" +
                        "nMissions", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMainBusinessGoals {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMai" +
                        "nBusinessGoals", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMainIndex {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMai" +
                        "nIndex", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMainMarket {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMai" +
                        "nMarket", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMainNewsfeeds {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToClickOnMainViewBottomBarButton_NavigationMai" +
                        "nNewsfeeds", resourceCulture);
            }
        }
        
        internal static string ComMotivistDevelopment_CheckFromMessageDialog_DialogPositiveButton {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckFromMessageDialog_DialogPositiveButton", resourceCulture);
            }
        }
    }
}
