//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiumClientMobile.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessibilityIds {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessibilityIds() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppiumClientMobile.Properties.AccessibilityIds", typeof(AccessibilityIds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StartAppOtpActivity_SendPhoneNumberToRequiredField_LoginPhoneNumber_ {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_SendPhoneNumberToRequiredField_LoginPhoneNumber_", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToEnterNumberScreen_PhoneNumber {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToEnterNumberScreen_PhoneNumber", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToEnterNumberScreen_ExpectedNumber {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToEnterNumberScreen_ExpectedNumber", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToEnterNumberScreen_LoginButton {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToEnterNumberScreen_LoginButton", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToGetOtpCodeFromOtpScreenOrGetErrorMessage_OtpTextView {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToGetOtpCodeFromOtpScreenOrGetErrorMessage_OtpTex" +
                        "tView", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToGetOtpCodeFromOtpScreenOrGetErrorMessage_DialogNegativeButton {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToGetOtpCodeFromOtpScreenOrGetErrorMessage_Dialog" +
                        "NegativeButton", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToGetOtpCodeFromOtpScreenOrGetErrorMessage_ErrorMessageText {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToGetOtpCodeFromOtpScreenOrGetErrorMessage_ErrorM" +
                        "essageText", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToOtpEnterOtpCodeScreenWithWaitThreeMinAfterOtpRetry_LoginOtpRetryButton {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToOtpEnterOtpCodeScreenWithWaitThreeMinAfterOtpRe" +
                        "try_LoginOtpRetryButton", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToOtpEnterOtpCodeScreen_OtpEditText {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToOtpEnterOtpCodeScreen_OtpEditText", resourceCulture);
            }
        }
        
        internal static string StartAppOtpActivity_CheckAbilityToOtpEnterOtpCodeScreen_LoginOtpVerify {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToOtpEnterOtpCodeScreen_LoginOtpVerify", resourceCulture);
            }
        }
    }
}
