//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiumClientMobile.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Capabilities {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Capabilities() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppiumClientMobile.Properties.Capabilities", typeof(Capabilities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GeneralCapabilities_Android_PlatformVersion {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Android_PlatformVersion", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Android_DeviceName {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Android_DeviceName", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Ios_DeviceName {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Ios_DeviceName", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_AnyDevice_OrientationPortrait {
            get {
                return ResourceManager.GetString("GeneralCapabilities_AnyDevice_OrientationPortrait", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_AnyDevice_OrientationLandscape {
            get {
                return ResourceManager.GetString("GeneralCapabilities_AnyDevice_OrientationLandscape", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Android_PlatformName {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Android_PlatformName", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Ios_PlatformName {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Ios_PlatformName", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Ios_PlatformVersion {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Ios_PlatformVersion", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Ios_AppPath_OnMac {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Ios_AppPath_OnMac", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Android_AppPath_OnMac {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Android_AppPath_OnMac", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Android_AppPackageName {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Android_AppPackageName", resourceCulture);
            }
        }
        
        internal static string GeneralCapabilities_Android_AppWaitActivity {
            get {
                return ResourceManager.GetString("GeneralCapabilities_Android_AppWaitActivity", resourceCulture);
            }
        }
    }
}
