//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiumClientMobile.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppiumClientMobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] motivistv5 {
            get {
                object obj = ResourceManager.GetObject("motivistv5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PathToLinuxNode {
            get {
                object obj = ResourceManager.GetObject("PathToLinuxNode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PathToMacOSNode {
            get {
                object obj = ResourceManager.GetObject("PathToMacOSNode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PathToWindowsNode {
            get {
                object obj = ResourceManager.GetObject("PathToWindowsNode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string AppiumLocalServerLaunchingTest_BeforeAll_Server_Test_IP__ {
            get {
                return ResourceManager.GetString("AppiumLocalServerLaunchingTest_BeforeAll_Server_Test_IP__", resourceCulture);
            }
        }
        
        public static string StartAppOtpActivity_CheckAbilityToEnterNumberScreen_Current_Activity__ {
            get {
                return ResourceManager.GetString("StartAppOtpActivity_CheckAbilityToEnterNumberScreen_Current_Activity__", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_CheckAbilityToGetThreeMinutesError_WaitMessage {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_CheckAbilityToGetThreeMinutesError_WaitMessage", resourceCulture);
            }
        }
        
        public static string CheckIfAppInstalled_IsInstalledMessage__ {
            get {
                return ResourceManager.GetString("CheckIfAppInstalled_IsInstalledMessage__", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_Contexts_ReceivedOtpCodeMessage {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_Contexts_ReceivedOtpCodeMessage", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_Messages_UnknownErrorMessage {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_Messages_UnknownErrorMessage", resourceCulture);
            }
        }
        
        public static string Helpers_AppiumServers_ServerAddress {
            get {
                return ResourceManager.GetString("Helpers_AppiumServers_ServerAddress", resourceCulture);
            }
        }
        
        public static string StartAppOtpUiViewController_CheckAbilityToEnterNumberView_CurrentWindowHandle {
            get {
                return ResourceManager.GetString("StartAppOtpUiViewController_CheckAbilityToEnterNumberView_CurrentWindowHandle", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_OtpDialogView_DialogProcessText {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_OtpDialogView_DialogProcessText", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_Contexts_LoginPhoneNumber {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_Contexts_LoginPhoneNumber", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_Contexts_CorrectLoginMessage {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_Contexts_CorrectLoginMessage", resourceCulture);
            }
        }
        
        public static string ComMotivistDevelopment_Contexts_CorrectMessage {
            get {
                return ResourceManager.GetString("ComMotivistDevelopment_Contexts_CorrectMessage", resourceCulture);
            }
        }
    }
}
